#!/usr/bin/env bash
set -e

echo "Installing OpenAB Broker..."

if [[ -z "${_REMOTE_USER:-}" || -z "${_REMOTE_USER_HOME:-}" ]]; then
    echo "ERROR: _REMOTE_USER / _REMOTE_USER_HOME not set — is devcontainers/common-utils applied?"
    exit 1
fi

# --- 1. System dependencies ------------------------------------------------
apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates curl git procps
rm -rf /var/lib/apt/lists/*

# --- 2. Locate cargo (from devdesk-base) -----------------------------------
CARGO_BIN="$_REMOTE_USER_HOME/.local/share/mise/shims/cargo"
if [[ ! -x "$CARGO_BIN" ]]; then
    CARGO_BIN="$_REMOTE_USER_HOME/.cargo/bin/cargo"
fi
if [[ ! -x "$CARGO_BIN" ]]; then
    echo "ERROR: cargo not found. Install rust via devdesk-base 'packages' option (e.g. rust@latest)."
    exit 1
fi

# --- 3. Build openab from source -------------------------------------------
# Resolve version → git ref:
#   'latest'      → main branch (bleeding edge)
#   '0.7.6' etc.  → tag v0.7.6 (auto-prepend 'v' to semver-looking values)
#   anything else → used verbatim as a git ref
if [[ "$VERSION" == "latest" ]]; then
    OPENAB_REF="main"
elif [[ "$VERSION" =~ ^[0-9] ]]; then
    OPENAB_REF="v$VERSION"
else
    OPENAB_REF="$VERSION"
fi

echo "Cloning openab (version='${VERSION}' → ref='${OPENAB_REF}') from ${REPOURL}..."
BUILD_DIR=$(mktemp -d)
chown "$_REMOTE_USER:$_REMOTE_USER" "$BUILD_DIR"
su - "$_REMOTE_USER" -c "
    set -e
    cd '$BUILD_DIR'
    git clone '$REPOURL' src
    cd src
    git checkout '$OPENAB_REF'
    echo 'Building openab (release) — this may take several minutes...'
    '$CARGO_BIN' build --release
"
install -m 0755 "$BUILD_DIR/src/target/release/openab" /usr/local/bin/openab
rm -rf "$BUILD_DIR"
echo "openab binary installed at /usr/local/bin/openab"

# --- 5. Write config.toml template -----------------------------------------
mkdir -p "$(dirname "$CONFIGPATH")"

# Format allowed_channels as TOML array
if [[ -n "$ALLOWEDCHANNELS" ]]; then
    ALLOWED_TOML=""
    IFS=',' read -ra CH_ARRAY <<< "$ALLOWEDCHANNELS"
    for ch in "${CH_ARRAY[@]}"; do
        ch="$(echo "$ch" | tr -d '[:space:]')"
        [[ -z "$ch" ]] && continue
        ALLOWED_TOML="${ALLOWED_TOML:+$ALLOWED_TOML, }\"$ch\""
    done
else
    ALLOWED_TOML='"REPLACE_WITH_CHANNEL_ID"'
fi

case "$DEFAULTAGENT" in
    kiro-cli)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "kiro-cli"
args = ["acp", "--trust-all-tools"]
working_dir = "__WORKDIR__"
AEOF
)
        ;;
    claude)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "claude"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}" }
AEOF
)
        ;;
    codex)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "codex"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }
AEOF
)
        ;;
    gemini)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "gemini"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }
AEOF
)
        ;;
    copilot)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "copilot"
args = ["--acp", "--stdio"]
working_dir = "__WORKDIR__"
AEOF
)
        ;;
    *)
        echo "ERROR: unknown defaultAgent '$DEFAULTAGENT'"
        exit 1
        ;;
esac
AGENT_BLOCK="${AGENT_BLOCK//__WORKDIR__/$_REMOTE_USER_HOME}"

cat > "$CONFIGPATH" <<CFGEOF
# Generated by devcontainer-features/openab-broker
# Edit or override by remounting this file.

[discord]
bot_token = "\${DISCORD_BOT_TOKEN}"
allowed_channels = [${ALLOWED_TOML}]

${AGENT_BLOCK}

[pool]
max_sessions = ${MAXSESSIONS}
session_ttl_hours = 24

[reactions]
enabled = true
remove_after_reply = false

CFGEOF

chmod 0644 "$CONFIGPATH"
echo "Wrote config template to $CONFIGPATH"

# --- 6. Supervisor config --------------------------------------------------
mkdir -p /etc/supervisor/conf.d
AUTOSTART_VALUE="false"
[[ "$AUTOSTART" == "true" ]] && AUTOSTART_VALUE="true"

cat > /etc/supervisor/conf.d/openab.conf <<SUPEOF
[program:openab]
command=/usr/local/bin/openab run ${CONFIGPATH}
directory=${_REMOTE_USER_HOME}
autostart=${AUTOSTART_VALUE}
startsecs=5
autorestart=true
startretries=3
stderr_logfile=/var/log/openab.err.log
stdout_logfile=/var/log/openab.log
user=${_REMOTE_USER}
environment=PATH="${_REMOTE_USER_HOME}/.local/bin:${_REMOTE_USER_HOME}/.local/share/mise/shims:/usr/local/bin:/usr/bin:/bin",HOME="${_REMOTE_USER_HOME}"
SUPEOF

# --- 7. Entrypoint hook ----------------------------------------------------
cat > /usr/local/bin/devdesk-openab-entrypoint <<'ENTRYPOINTEOF'
#!/bin/bash

if ! pgrep -x supervisord > /dev/null; then
    echo "→ Starting supervisord..."
    sudo supervisord -c /etc/supervisor/supervisord.conf
fi

sudo supervisorctl reread 2>/dev/null || true
sudo supervisorctl update 2>/dev/null || true

if [[ -n "$DISCORD_BOT_TOKEN" ]]; then
    sudo supervisorctl start openab 2>/dev/null || true
else
    echo "openab: DISCORD_BOT_TOKEN not set — broker not started. Run 'sudo supervisorctl start openab' after exporting the token."
fi

exec "$@"
ENTRYPOINTEOF
chmod +x /usr/local/bin/devdesk-openab-entrypoint

echo "OpenAB Broker installation complete!"
