#!/usr/bin/env bash
set -e

echo "Installing OpenAB Broker..."

if [[ -z "${_REMOTE_USER:-}" || -z "${_REMOTE_USER_HOME:-}" ]]; then
    echo "ERROR: _REMOTE_USER / _REMOTE_USER_HOME not set — is devcontainers/common-utils applied?"
    exit 1
fi

# --- 1. System dependencies ------------------------------------------------
apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates curl git procps
rm -rf /var/lib/apt/lists/*

# --- 2. Locate cargo (from devdesk-base) -----------------------------------
CARGO_BIN="$_REMOTE_USER_HOME/.local/share/mise/shims/cargo"
if [[ ! -x "$CARGO_BIN" ]]; then
    CARGO_BIN="$_REMOTE_USER_HOME/.cargo/bin/cargo"
fi
if [[ ! -x "$CARGO_BIN" ]]; then
    echo "ERROR: cargo not found. Install rust via devdesk-base 'packages' option (e.g. rust@latest)."
    exit 1
fi

# --- 3. Build openab from source -------------------------------------------
# Resolve version → git ref:
#   'latest'      → main branch (bleeding edge)
#   '0.7.6' etc.  → tag v0.7.6 (auto-prepend 'v' to semver-looking values)
#   anything else → used verbatim as a git ref
if [[ "$VERSION" == "latest" ]]; then
    OPENAB_REF="main"
elif [[ "$VERSION" =~ ^[0-9] ]]; then
    OPENAB_REF="v$VERSION"
else
    OPENAB_REF="$VERSION"
fi

echo "Cloning openab (version='${VERSION}' → ref='${OPENAB_REF}') from ${REPOURL}..."
BUILD_DIR=$(mktemp -d)
chown "$_REMOTE_USER:$_REMOTE_USER" "$BUILD_DIR"
su - "$_REMOTE_USER" -c "
    set -e
    cd '$BUILD_DIR'
    git clone '$REPOURL' src
    cd src
    git checkout '$OPENAB_REF'
    echo 'Building openab (release) — this may take several minutes...'
    '$CARGO_BIN' build --release
"
install -m 0755 "$BUILD_DIR/src/target/release/openab" /usr/local/bin/openab
rm -rf "$BUILD_DIR"
echo "openab binary installed at /usr/local/bin/openab"

# --- 5. Write config.toml template -----------------------------------------
mkdir -p "$(dirname "$CONFIGPATH")"

# Format comma-separated IDs into a TOML array body (quoted), or a fallback when empty.
csv_to_toml() {
    local csv="$1" fallback="$2" out="" item
    if [[ -n "$csv" ]]; then
        IFS=',' read -ra _arr <<< "$csv"
        for item in "${_arr[@]}"; do
            item="$(echo "$item" | tr -d '[:space:]')"
            [[ -z "$item" ]] && continue
            out="${out:+$out, }\"$item\""
        done
        printf '%s' "$out"
    else
        printf '%s' "$fallback"
    fi
}
ALLOWED_TOML="$(csv_to_toml "$ALLOWEDCHANNELS" '"REPLACE_WITH_CHANNEL_ID"')"
ROLE_TOML="$(csv_to_toml "${ALLOWEDROLEIDS:-}" '')"
TRUSTED_TOML="$(csv_to_toml "${TRUSTEDBOTIDS:-}" '')"
USERS_TOML="$(csv_to_toml "${ALLOWEDUSERS:-}" '')"

# The cron example job posts into the first allowed channel, else a placeholder.
if [[ -n "$ALLOWEDCHANNELS" ]]; then
    CRON_CHANNEL="$(echo "$ALLOWEDCHANNELS" | cut -d, -f1 | tr -d '[:space:]')"
else
    CRON_CHANNEL="REPLACE_WITH_CHANNEL_ID"
fi

case "$DEFAULTAGENT" in
    kiro-cli)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "kiro-cli"
args = ["acp", "--trust-all-tools"]
working_dir = "__WORKDIR__"
AEOF
)
        ;;
    claude)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "claude"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}" }
AEOF
)
        ;;
    codex)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "codex"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }
AEOF
)
        ;;
    gemini)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "gemini"
args = ["--acp"]
working_dir = "__WORKDIR__"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }
AEOF
)
        ;;
    copilot)
        AGENT_BLOCK=$(cat <<'AEOF'
[agent]
command = "copilot"
args = ["--acp", "--stdio", "--add-dir", "__HOME__/.copilot", "--add-dir", "__HOME__/.claude"]
working_dir = "__WORKDIR__"
AEOF
)
        ;;
    *)
        echo "ERROR: unknown defaultAgent '$DEFAULTAGENT'"
        exit 1
        ;;
esac
AGENT_BLOCK="${AGENT_BLOCK//__HOME__/$_REMOTE_USER_HOME}"
AGENT_BLOCK="${AGENT_BLOCK//__WORKDIR__/$_REMOTE_USER_HOME/workspaces}"

cat > "$CONFIGPATH" <<CFGEOF
# Generated by devcontainer-features/openab-broker
# Edit or override by remounting this file.

[discord]
bot_token = "\${DISCORD_BOT_TOKEN}"
allowed_channels = [${ALLOWED_TOML}]
trusted_bot_ids = [${TRUSTED_TOML}]
allowed_users = [${USERS_TOML}]
allow_bot_messages = "mentions"
allow_user_messages = "multibot-mentions"
max_bot_turns = 20
allow_dm = true
allowed_role_ids = [${ROLE_TOML}]
message_processing_mode = "per-thread"
# Batched-mode tuning. Defaults shown; bump if you see "channel full" warnings
# or want larger batches.
max_buffered_messages = 10
max_batch_tokens = 24000

${AGENT_BLOCK}
# Explicit env to inject into the agent process (overrides inherit_env on conflict).
# env = { GH_TOKEN = "\${GH_TOKEN}" }
# Whitelist of host env vars to pass through. Empty list = nothing inherited.
# inherit_env = ["PATH", "HOME", "USER", "LANG", "GH_TOKEN"]

[pool]
max_sessions = ${MAXSESSIONS}
session_ttl_hours = 24
# Hard timeout for a single agent turn; if exceeded the connection is killed.
# prompt_hard_timeout_secs = 1800
# How often the supervisor pings the agent process for liveness.
# liveness_check_secs = 30

[reactions]
enabled = true
remove_after_reply = false
# Tool-call display: "full" / "compact" / "none".
# tool_display = "compact"

[markdown]
# Pulldown-cmark table conversion mode: "code" / "bullets" / "off".
# Discord doesn't render markdown tables; "code" wraps them in a fenced block.
tables = "code"

# --- Optional: gateway bridge -------------------------------------------------
# Uncomment and adjust if you have openab-gateway running and want this broker
# to bridge to Telegram / LINE / Feishu / Google Chat / MS Teams through it.
#
# [gateway]
# url = "ws://localhost:8080/ws"
# platform = "telegram"          # session key namespacing
# token = "shared-secret"        # WS auth (optional but recommended)
# bot_username = "my_bot"        # @mention gating in groups
# streaming = true
# message_processing_mode = "batched"
# max_buffered_messages = 10
# max_batch_tokens = 24000

# --- Optional: speech-to-text ------------------------------------------------
# Enables transcription of voice attachments. Echoes the transcript back into
# the thread before the agent reply (so users see what the bot heard).
#
# [stt]
# enabled = false
# api_key = "\${OPENAI_API_KEY}"
# model = "whisper-1"
# base_url = "https://api.openai.com/v1"
# echo_transcript = true

# --- Cron jobs ---------------------------------------------------------------
# In-process scheduler — openab fires these on its own tokio runtime, no OS
# crond needed. usercron picks up user-defined jobs from
# \$HOME/.openab/usercron.toml; [[cron.jobs]] entries below are checked into
# this config.

[cron]
usercron_enabled = true
usercron_path = "usercron.toml"

# Example: weekday 09:00 morning briefing in the allowed channel.
# Schedule is standard 5-field POSIX cron; day-of-week supports both numeric
# (0=Sun..6=Sat) and name (Mon, Fri, Mon-Fri) tokens. Disable by setting
# enabled = false, or delete the block entirely.
[[cron.jobs]]
enabled = false
schedule = "0 9 * * MON-FRI"
channel = "${CRON_CHANNEL}"
message = "Morning! Summarise what's on the plate today across my active projects, and surface anything urgent or overdue."
platform = "discord"
sender_name = "scheduler"
timezone = "Asia/Taipei"
# thread_id = "..."   # uncomment to post into an existing thread instead of channel root

CFGEOF

chmod 0644 "$CONFIGPATH"
echo "Wrote config template to $CONFIGPATH"

# --- 6. Supervisor config --------------------------------------------------
mkdir -p /etc/supervisor/conf.d
AUTOSTART_VALUE="false"
[[ "$AUTOSTART" == "true" ]] && AUTOSTART_VALUE="true"

cat > /etc/supervisor/conf.d/openab.conf <<SUPEOF
[program:openab]
command=/usr/local/bin/openab run ${CONFIGPATH}
directory=${_REMOTE_USER_HOME}
autostart=${AUTOSTART_VALUE}
startsecs=5
autorestart=true
startretries=3
stderr_logfile=/var/log/openab.err.log
stdout_logfile=/var/log/openab.log
user=${_REMOTE_USER}
environment=PATH="${_REMOTE_USER_HOME}/.local/bin:${_REMOTE_USER_HOME}/.local/share/mise/shims:/usr/local/bin:/usr/bin:/bin",HOME="${_REMOTE_USER_HOME}"
SUPEOF

# --- 7. Entrypoint hook ----------------------------------------------------
cat > /usr/local/bin/devdesk-openab-entrypoint <<'ENTRYPOINTEOF'
#!/bin/bash

if ! pgrep -x supervisord > /dev/null; then
    echo "→ Starting supervisord..."
    sudo supervisord -c /etc/supervisor/supervisord.conf
fi

sudo supervisorctl reread 2>/dev/null || true
sudo supervisorctl update 2>/dev/null || true

if [[ -n "$DISCORD_BOT_TOKEN" ]]; then
    sudo supervisorctl start openab 2>/dev/null || true
else
    echo "openab: DISCORD_BOT_TOKEN not set — broker not started. Run 'sudo supervisorctl start openab' after exporting the token."
fi

exec "$@"
ENTRYPOINTEOF
chmod +x /usr/local/bin/devdesk-openab-entrypoint

echo "OpenAB Broker installation complete!"
